import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.scss";

const roboto = Roboto({
  subsets: ["cyrillic", "latin"],
  weight: ["300", "500", "400", "700", "100"],
});

export const metadata: Metadata = {
  title: "Pomodoro App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        {children}
        <div id="modal" />
      </body>
    </html>
  );
}
